export const mockDogs = [
    {
      id: 1,
      name: "Bailey",
      img: "https://images.pexels.com/photos/1865394/pexels-photo-1865394.jpeg",
      breed: "Golden Retriever",
      age: "3 years",
      gender: "Male",
      location: "5 miles",
      height: "24 inch",
      weight: "65 lb",
      owner: "Emily Johnson",
      description: "Loyal and loving family dog, always eager to play fetch.",
      liked: false,
    },
    {
      id: 2,
      name: "Bella",
      img: "https://images.pexels.com/photos/4587994/pexels-photo-4587994.jpeg",
      breed: "Labrador",
      age: "2 years",
      gender: "Female",
      location: "12 miles",
      height: "23 inch",
      weight: "70 lb",
      owner: "Mark Smith",
      description: "Energetic and friendly, loves swimming and long walks.",
      liked: false,
    },
    {
      id: 3,
      name: "Max",
      img: "https://images.pexels.com/photos/1709003/pexels-photo-1709003.jpeg",
      breed: "German Shepherd",
      age: "4 years",
      gender: "Male",
      location: "15 miles",
      height: "26 inch",
      weight: "75 lb",
      owner: "Anna Brown",
      description: "Highly intelligent and protective, great with kids.",
      liked: false,
    },
    {
      id: 4,
      name: "Lucy",
      img: "https://images.pexels.com/photos/4587972/pexels-photo-4587972.jpeg",
      breed: "Beagle",
      age: "1 year",
      gender: "Female",
      location: "8 miles",
      height: "14 inch",
      weight: "22 lb",
      owner: "Chris Evans",
      description: "Curious and playful, loves exploring new scents.",
      liked: false,
    },
    {
      id: 5,
      name: "Charlie",
      img: "https://images.pexels.com/photos/4587983/pexels-photo-4587983.jpeg",
      breed: "Corgi",
      age: "3 years",
      gender: "Male",
      location: "3 miles",
      height: "12 inch",
      weight: "30 lb",
      owner: "Sophia Carter",
      description: "Charming and energetic, a true herder at heart.",
      liked: false,
    },
    {
      id: 6,
      name: "Molly",
      img: "https://images.pexels.com/photos/4587986/pexels-photo-4587986.jpeg",
      breed: "Poodle",
      age: "5 years",
      gender: "Female",
      location: "18 miles",
      height: "22 inch",
      weight: "45 lb",
      owner: "Liam Wilson",
      description: "Elegant and smart, loves attention and learning tricks.",
      liked: false,
    },
    {
      id: 7,
      name: "Rocky",
      img: "https://images.pexels.com/photos/4587987/pexels-photo-4587987.jpeg",
      breed: "Boxer",
      age: "2 years",
      gender: "Male",
      location: "10 miles",
      height: "25 inch",
      weight: "68 lb",
      owner: "James Green",
      description: "Strong and loyal, enjoys running and playing.",
      liked: false,
    },
    {
      id: 8,
      name: "Luna",
      img: "https://images.pexels.com/photos/4587990/pexels-photo-4587990.jpeg",
      breed: "Husky",
      age: "3 years",
      gender: "Female",
      location: "20 miles",
      height: "23 inch",
      weight: "60 lb",
      owner: "Olivia White",
      description: "Adventurous and vocal, loves the cold and long hikes.",
      liked: false,
    },
    {
      id: 9,
      name: "Cooper",
      img: "https://images.pexels.com/photos/4587976/pexels-photo-4587976.jpeg",
      breed: "Dalmatian",
      age: "2 years",
      gender: "Male",
      location: "25 miles",
      height: "24 inch",
      weight: "55 lb",
      owner: "Noah Hall",
      description: "Energetic and social, loves running and meeting new friends.",
      liked: false,
    },
    {
      id: 10,
      name: "Daisy",
      img: "https://images.pexels.com/photos/4587978/pexels-photo-4587978.jpeg",
      breed: "Shih Tzu",
      age: "4 years",
      gender: "Female",
      location: "2 miles",
      height: "10 inch",
      weight: "15 lb",
      owner: "Mason King",
      description: "Gentle and affectionate, enjoys cuddles and quiet time.",
      liked: false,
    },
    {
      id: 11,
      name: "Oliver",
      img: "https://images.pexels.com/photos/4587989/pexels-photo-4587989.jpeg",
      breed: "Great Dane",
      age: "5 years",
      gender: "Male",
      location: "30 miles",
      height: "32 inch",
      weight: "120 lb",
      owner: "Isabella Scott",
      description: "Gentle giant, loves kids and being part of the family.",
      liked: false,
    },
    {
      id: 12,
      name: "Zoey",
      img: "https://images.pexels.com/photos/4587974/pexels-photo-4587974.jpeg",
      breed: "Chihuahua",
      age: "1 year",
      gender: "Female",
      location: "1 mile",
      height: "8 inch",
      weight: "5 lb",
      owner: "Charlotte Harris",
      description: "Small but mighty, loves attention and being pampered.",
      liked: false,
    },
    // Add 13 more entries here for a total of 25 unique dogs.
  ];



export type DogType = { 
    id: number;
    name: string;
    img: string;
    breed: string;
    age: string;
    gender: string;
    location: string;
    height : string;
    weight:  string;    
    owner: string;
    description: string;
    liked: boolean;
}